#!/bin/sh

pipe_path="/tmp/dwm_status.fifo"

[ ! -e $pipe_path ] && mkfifo $pipe_path

clock -f 'C%a %d %b %H:%M' -si 10 > $pipe_path &
battery -f 'B%s %i' -si 60 > $pipe_path &
temp -f 'T%3.1f' -si 15 > $pipe_path &
vol V > $pipe_path &

while read -r line; do
    case $line in
        B*)
            fbat="${line#?}"
            s=$(echo $fbat | cut -d' ' -f1)
            n=$(echo $fbat | cut -d' ' -f2)
            
            case $s in
                Discharging)
                    bat="-$n"
                ;;
                Charging)
                    bat="+$n"
                ;;
                Full)
                    bat="f$n"
                ;;
            esac
            ;;
        C*)
            clock="${line#?}" 
            ;;
        V*)
            vol="${line#?}" 
            ;;
        T*)
            temp="${line#?}"
            ;;
    esac

    /usr/bin/xsetroot -name " VOL $vol | BAT $bat | TEMP $temp | $clock "
done < $pipe_path
