#!/bin/sh

stdbuf -oL amixer events | grep --line-buffered 'event value: numid=10' |
    while IFS= read -r line; do
        amixer -M get Master |
            awk -v fmt=$1 '/Mono:/ { gsub(/[\[\]]/, "", $0); print fmt $4 }'
    done
